version: 2

updates:
  - package-ecosystem: npm
    directory: /backend
    schedule:
      interval: weekly
    groups:
      backend-dependencies:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /backend
    schedule:
      interval: weekly
    groups:
      backend-image:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /frontend
    schedule:
      interval: weekly
    groups:
      frontend-image:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      workflow-actions:
        patterns:
          - "*"
