apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy-service
  labels:
    app.kubernetes.io/name: reverse-proxy
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: demo-kind
spec:
  selector:
    app.kubernetes.io/name: reverse-proxy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
